server:
  port: ${SPRING_SERVER_PORT:7878}
  tomcat:
    max-swallow-size: -1

spring:
  banner:
    image:
      location:
        /images/banner.png
  servlet.multipart:
    max-file-size: -1
    max-request-size: -1
  main.allow-bean-definition-overriding: true
  output.ansi.enabled: DETECT
  jpa:
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      temp.use_jdbc_metadata_defaults: false
      jdbc.batch_size: 40
      order_inserts: true
    open-in-view: false
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
    jmx:
      enabled: false
  liquibase:
    change-log: classpath:/db/changelog/changelog-main.xml
    enabled: false
    liquibase-schema:

app:
  host: ${SPRING_HOST_NAME:localhost}
  port: ${SPRING_SERVER_PORT:7878}
  selenium.host: ${SPRING_SELENIUM_HOST:localhost}
  url:
    page-source: http://${SPRING_CONTAINER_NAME:localhost}:${app.port}/pages
    report: healenium/report
  selector:
    key:
      url-for-key: ${KEY_SELECTOR_URL:false}
      path-for-key: ${KEY_SELECTOR_PATH:false}
  metrics:
    allow: ${COLLECT_METRICS:true}
  healing:
    elements: ${FIND_ELEMENTS_AUTO_HEALING:false}

cloud:
  aws:
    region:
      static: eu-central-1
    stack:
      auto: false

logging:
  level:
    ROOT: ${SPRING_LOG_LEVEL:INFO}
    org.springframework: INFO
    org.mongodb.driver.connection: WARN
    healenium: ${HLM_LOG_LEVEL:INFO}
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS,Europe/Moscow} %clr(%5p) %clr(${PID:- }){magenta} %clr(-){faint} %clr([%11.11t]){faint} %clr(%-32.32logger{30}){cyan} %clr(:){faint} %replace(%m){''[\n\r]'',''\\n ''} %replace(%ex){''[\r\n]'', ''\\n ''}%nopex%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS,Europe/Moscow} %clr(%5p) %clr(${PID:- }){magenta} %clr(-){faint} %clr([%11.11t]){faint} %clr(%-32.32logger{30}){cyan} %clr(:){faint} %replace(%m){''[\n\r]'',''\\n ''} %replace(%ex){''[\r\n]'', ''\\n ''}%nopex%n'
  file:
    name: ./logs/healenium-backend.log